apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: backend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        command: ["python", "-u", "/backend.py"]
        image: python:3.7-stretch
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: backendcode
            mountPath: "/backend.py"
            subPath: "backend.py"
      volumes:
        - name: backendcode
          configMap:
            name: backendcode

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend
        subset: v1
    timeout: 60s

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
spec:
  host: backend
  subsets:
  - name: v1
    labels:
      version: v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backendcode
data:
  backend.py: |
    #!/usr/bin/env python

    from http.server import BaseHTTPRequestHandler, HTTPServer
    from time import sleep

    PORT = 4000
    SLEEP_TIME = 22

    class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):

        def do_GET(self):
            sleep(SLEEP_TIME)

            self.send_response(200)
            self.send_header('Content-type','text/html')
            self.end_headers()
            message = "backend-response"

            self.wfile.write(bytes(message, "utf8"))
            return

    def run():
        print('starting server...')
        server_address = ('0.0.0.0', PORT)
        httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
        print('running server...')
        httpd.serve_forever()

    run()
